### ISSUE TITLE
support collect log for operator cluster

### ISSUE THREAD

**Issue by nexustar** [pingcap/diag#435]
## Feature Request

**Is your feature request related to a problem? Please describe:**

**Describe the feature you'd like:**

**Why the featue is needed:**

**Describe alternatives you've considered:**

**Teachability, Documentation, Adoption, Migration Strategy:**

**Comment by kaaaaaaang** [comment]
option 1: collect logs from k8s, most log are not rotated when collect
option 2: collect log files from pod
